name: DevourNow
favicon: null
layout_spectrum: 0.72791
typography_spectrum: 0.30844
title: Devour Now
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010600'
    - '#fe9600'
    - '#ac6700'
    - '#b9e400'
    - '#fce49e'
  brandStrength: 0.6875
  lightness: 0.33988106809556484
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
