name: DevourNow
favicon: null
layout_spectrum: 0.57556
typography_spectrum: 0.49645
title: Devour Now
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010600'
    - '#fe9600'
    - '#ac6700'
    - '#b9e400'
    - '#fce49e'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
